### ISSUE TITLE
First assignments

### ISSUE THREAD

**Issue by asmateus** [karolaya/taolu-enhancer#1]
### Python wrapper for C/C++ code
In general you can build modules for python in C and C++, this modules, if built in a specific manner, can be compiled and used within a python (a Cython implementation of it, which is most likely the case) program. Your job here is simple: explore what is needed to do such a thing and implement in C a function to calculate the sum of an `array`. This function should then be imported and used in python with`lists`, like this:

    >> import arrsum
    >> a = [1, 2, 3]
    >> arrsum.sum(a)
    6

This will be really helpful to build PySkeltrack as a module.

### Database and Connectors construction
This stage can be treated at the same time as the others. Field test is required: take several depth videos of the *form* for training (like 100 videos), with this we will construct the database. As the database will be probably large, some thought must be given to design it. Also create a IO module that handles the database connection in an elegant manner. All exposure to the outer world is through this module.

### PySkeltrack C++ module
Write a working C++ application that listens to the kinect buffer and handles it to the Skeltrack script. The application may also buffer videos saved in the database. This will be wrapped up and made a module accessible from python.

### UI development
Create the graphical user interface, the user needs to be able to train the system, start a session, see previous results, export the data, see the video input in real time with a counter of correct and incorrect movements. This UI should not clutter the code and should be standalone, as it will be managed by different processes outside of it. 

### Documentation and help
This is simple: document what you do and what you will do. Also the main function `enhancer` has a help flag (`--help`). Please contribute to extend this help, maybe we can even create a `man` page :).

**Comment by juliansibaja84** [comment]
I will be working on __Python wrapper for C/C++ code__ and __UI development__

**Comment by karolaya** [comment]
Database and Connectors construction.

**Comment by asmateus** [comment]
I will work in **PySkeltrack C++ module**
